PermitRootLogin prohibit-password
PasswordAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile /root/.ssh/authorized_keys /run/sshd/authorized_keys
HostKey /root/.ssh/ssh_host_rsa_key
HostKey /root/.ssh/ssh_host_ecdsa_key
HostKey /root/.ssh/ssh_host_ed25519_key
ClientAliveInterval 60
ClientAliveCountMax 3
TCPKeepAlive yes
